import turtle as trtl

painter = trtl.Turtle()
painter.hideturtle()
painter.speed(0)

# left half of upper body
painter.setheading(110)
painter.penup()
painter.goto(-75, -175)
painter.pendown()
painter.color("black", "#808080")
painter.begin_fill()
painter.forward(40)
for i in range(50):
    painter.forward(8)
    painter.right(1)
painter.forward(100)

# right half of upper body
h = painter.heading()
painter.setheading(-h)
painter.forward(100)
for i in range(50):
    painter.forward(8)
    painter.right(1)
painter.forward(40)
painter.goto(65, -175)
painter.goto(-75, -175)
painter.end_fill()

# left half of motor
painter.color("black", "#202020")
painter.begin_fill()
painter.setheading(290)
for i in range(10):
    painter.forward(8)
    painter.right(2)
painter.goto(-60, -255)

# right half of motor
painter.goto(53, -255)
painter.setheading(painter.heading()+180)
for i in range(10):
    painter.forward(8)
    painter.right(2)
painter.goto(65, -175)
painter.goto(-75, -175)
painter.end_fill()

# left fin
painter.color("black", "#606060")
painter.begin_fill()
painter.setheading(135)
painter.penup()
painter.goto(-90, -135)
painter.pendown()
painter.left(100)
painter.forward(50)
painter.circle(30, 50)
painter.forward(125)
painter.circle(5, 170)
painter.forward(70)
painter.circle(-50, 50)
painter.forward(10)
painter.goto(-90, -135)
painter.end_fill()

# right fin
painter.color("black", "#606060")
painter.begin_fill()
painter.setheading(45)
painter.penup()
painter.goto(80, -135)
painter.pendown()
painter.right(100)
painter.forward(50)
painter.circle(-30, 50)
painter.forward(125)
painter.circle(-5, 170)
painter.forward(70)
painter.circle(50, 50)
painter.forward(10)
painter.goto(80, -135)
painter.end_fill()

# right fin
painter.color("black", "#606060")
painter.begin_fill()
painter.setheading(270)
painter.penup()
painter.goto(0, -255)
painter.pendown()
painter.forward(50)
painter.circle(-5, 180)
painter.forward(50)
painter.goto(0, -255)
painter.end_fill()

# blue logo
painter.setheading(60)
painter.penup()
painter.goto(-62, 82)
painter.color("black", "#3571A3")
painter.begin_fill()
painter.pendown()
for i in range(20):
    painter.forward(3)
    painter.right(3)
painter.setheading(0)
painter.forward(10)
for i in range(20):
    painter.forward(3)
    painter.right(3)
painter.goto(48, 82)
painter.setheading(270)
painter.forward(35)
painter.circle(-30, 90)
painter.goto(-32, 17)
painter.circle(30, 90)
painter.forward(25)
painter.setheading(180)
painter.forward(15)
painter.setheading(150)
for i in range(20):
    painter.forward(3)
    painter.right(3)
painter.setheading(90)
painter.forward(6)
for i in range(20):
    painter.forward(3)
    painter.right(3)
painter.goto(-78, 67)
painter.goto(0, 67)
painter.goto(0, 72)
painter.goto(-62, 72)
painter.goto(-62, 82)
painter.end_fill()
painter.color("black", "#FFFFFF")
painter.begin_fill()
painter.penup()
painter.goto(-37, 82)
painter.pendown()
painter.circle(5)
painter.end_fill()

# yellow logo
painter.setheading(240)
painter.penup()
painter.goto(52, -53)
painter.color("black", "#F3CC47")
painter.begin_fill()
painter.pendown()
for i in range(20):
    painter.forward(3)
    painter.right(3)
painter.setheading(180)
painter.forward(10)
for i in range(20):
    painter.forward(3)
    painter.right(3)
painter.goto(-58, -53)
painter.setheading(90)
painter.forward(35)
painter.circle(-30, 90)
painter.goto(22, 12)
painter.circle(30, 90)
painter.forward(25)
painter.setheading(0)
painter.forward(15)
painter.setheading(330)
for i in range(20):
    painter.forward(3)
    painter.right(3)
painter.setheading(270)
painter.forward(6)
for i in range(20):
    painter.forward(3)
    painter.right(3)
print(painter.position())
painter.goto(70, -38)
painter.goto(0, -38)
painter.goto(0, -43)
painter.goto(52, -43)
painter.goto(52, -53)
painter.end_fill()
painter.color("black", "#FFFFFF")
painter.begin_fill()
painter.penup()
painter.goto(27, -53)
painter.pendown()
painter.circle(5)
painter.end_fill()


# create the turtle window and close it when the window is clicked
window = trtl.Screen()
window.exitonclick()
